

name: ensembl
class: sifter

outdir: ../graph

config:

    exons: ../output/ensembl/ensembl.exons.exon.json.gz
    exonsSchema: ../src/bmeg/bmeg-dictionary/gdcdictionary/schemas

    genes: ../output/ensembl/ensembl.genes.gene.json.gz
    genesSchema: ../src/bmeg/bmeg-dictionary/gdcdictionary/schemas

    transcripts: ../output/ensembl/ensembl.transcripts.transcript.json.gz
    transcriptsSchema: ../src/bmeg/bmeg-dictionary/gdcdictionary/schemas


inputs:

    exons:
        jsonLoad:
            input: "{{config.exons}}"

    genes:
        jsonLoad:
            input: "{{config.genes}}"

    transcripts:
        jsonLoad:
            input: "{{config.transcripts}}"


pipelines:

    exons-graph:
        - from: exons
        - graphBuild:
            schema: "{{config.exonsSchema}}"
            class: exon

    genes-graph:
        - from: genes
        - graphBuild:
            schema: "{{config.genesSchema}}"
            class: gene

    transcripts-graph:
        - from: transcripts
        - graphBuild:
            schema: "{{config.transcriptsSchema}}"
            class: transcript

