

name: gdc
class: sifter

outdir: ../graph

config:

    aliquotObject:
        type: File
        default: ../output/gdc/gdc.aliquotObject.aliquot.json.gz
    aliquotObjectSchema:
        type: Dir
        default: ../src/bmeg/bmeg-dictionary/gdcdictionary/schemas

    caseObject:
        type: File
        default: ../output/gdc/gdc.caseObject.case.json.gz
    caseObjectSchema:
        type: Dir
        default: ../src/bmeg/bmeg-dictionary/gdcdictionary/schemas

    sampleObject:
        type: File
        default: ../output/gdc/gdc.sampleObject.sample.json.gz
    sampleObjectSchema:
        type: Dir
        default: ../src/bmeg/bmeg-dictionary/gdcdictionary/schemas


inputs:

    aliquotObject:
        jsonLoad:
            input: "{{config.aliquotObject}}"

    caseObject:
        jsonLoad:
            input: "{{config.caseObject}}"

    sampleObject:
        jsonLoad:
            input: "{{config.sampleObject}}"


pipelines:

    aliquotObject-graph:
        - from: aliquotObject
        - graphBuild:
            schema: "{{config.aliquotObjectSchema}}"
            class: aliquot

    caseObject-graph:
        - from: caseObject
        - graphBuild:
            schema: "{{config.caseObjectSchema}}"
            class: case

    sampleObject-graph:
        - from: sampleObject
        - graphBuild:
            schema: "{{config.sampleObjectSchema}}"
            class: sample

