

name: pharmacodb_profiles
class: sifter

outdir: ../graph

config:

    cellSample:
        type: File
        default: ../output/pharmacodb/pharmacodb_profiles.cellSample.sample.json.gz
    cellSampleSchema:
        type: Dir
        default: ../src/bmeg/bmeg-dictionary/gdcdictionary/schemas

    drObject:
        type: File
        default: ../output/pharmacodb/pharmacodb_profiles.drObject.drug_response.json.gz
    drObjectSchema:
        type: Dir
        default: ../src/bmeg/bmeg-dictionary/gdcdictionary/schemas

    cellAliquot:
        type: File
        default: ../output/pharmacodb/pharmacodb_profiles.cellAliquot.aliquot.json.gz
    cellAliquotSchema:
        type: Dir
        default: ../src/bmeg/bmeg-dictionary/gdcdictionary/schemas

    cellCase:
        type: File
        default: ../output/pharmacodb/pharmacodb_profiles.cellCase.case.json.gz
    cellCaseSchema:
        type: Dir
        default: ../src/bmeg/bmeg-dictionary/gdcdictionary/schemas

    cellProject:
        type: File
        default: ../output/pharmacodb/pharmacodb_profiles.cellProject.project.json.gz
    cellProjectSchema:
        type: Dir
        default: ../src/bmeg/bmeg-dictionary/gdcdictionary/schemas


inputs:

    cellSample:
        jsonLoad:
            input: "{{config.cellSample}}"

    drObject:
        jsonLoad:
            input: "{{config.drObject}}"

    cellAliquot:
        jsonLoad:
            input: "{{config.cellAliquot}}"

    cellCase:
        jsonLoad:
            input: "{{config.cellCase}}"

    cellProject:
        jsonLoad:
            input: "{{config.cellProject}}"


pipelines:

    cellSample-graph:
        - from: cellSample
        - graphBuild:
            schema: "{{config.cellSampleSchema}}"
            class: sample

    drObject-graph:
        - from: drObject
        - graphBuild:
            schema: "{{config.drObjectSchema}}"
            class: drug_response

    cellAliquot-graph:
        - from: cellAliquot
        - graphBuild:
            schema: "{{config.cellAliquotSchema}}"
            class: aliquot

    cellCase-graph:
        - from: cellCase
        - graphBuild:
            schema: "{{config.cellCaseSchema}}"
            class: case

    cellProject-graph:
        - from: cellProject
        - graphBuild:
            schema: "{{config.cellProjectSchema}}"
            class: project

