
name: pfam_family
outdir: ../../output/pfam/

config:
  xmlDir:
    type: Dir
    default: ../../source/pfam/xmls/
  schema:
    type: Dir
    default: ../../src/bmeg/bmeg-dictionary/gdcdictionary/schemas/

inputs:
  pfamData:
    glob:
      input: "{{config.xmlDir}}/*.xml"
      xmlLoad: {}


pipelines:
  transform:
    - from: pfamData
    - project:
        mapping:
          pfam_id: "{{row.entry._attr.id[0]}}"
          accession: "{{row.entry._attr.accession[0]}}"
          comments: "{{row.entry.comment}}"
          description: "{{row.entry.description}}"
          submitter_id: "{{row.entry._attr.id[0]}}"
          project_id: Reference
          type: PfamFamily
    - map:
        method: adjust
        gpython: |
          def adjust(x):
            clan = []
            if "clan_membership" in x["entry"] and "clan_acc" in x["entry"]["clan_membership"]["_attr"]:
              clan.append( x["entry"]["clan_membership"]["_attr"]["clan_acc"][0] )
            x["pfam_clans"] = clan
            x["comments"] = x["comments"].strip()
            return x

    - objectCreate:
        class: pfam_family
        schema: "{{config.schema}}"

    - emit:
        name: test
