# the database
database:
  image: postgres:10.5-alpine
  # build:
  #   ./postgres/docker
  expose:
    - 5432
  ports:
   - "5432:5432"
  volumes:
    - ./:/src
  environment:
      POSTGRES_PASSWORD: postgres
    # - ./postgres/agensgraph/data:/home/agens/AgensGraph/data

# graph:
#   image: bitnine/agensgraph:v1.3.2
#   expose:
#     - 5432
#   ports:
#    - "5432:5432"
#   volumes:
#     - ./:/src
#     # - ./postgres/agensgraph/data:/home/agens/AgensGraph/data
#   # dummy entry point to keep container running
#   command: tail -f /dev/null

development:
  image: python:3.7
  volumes:
    - ./:/src
  links:
    - database
    # - graph
  # dummy entry point to keep container running
  command: tail -f /dev/null
