# the database
database:
  # image: postgres:9.6.5-alpine
  build:
    ./postgres/docker
  expose:
    - 5432
  ports:
   - "5432:5432"
  environment:
    POSTGRES_PASSWORD: password
  volumes:
    - ./:/src
    - ./postgres/data/:/var/lib/postgresql/data/

agensgraph:
  image: bitnine/agensgraph:v1.3.2
  expose:
    - 5433
  ports:
   - "5433:5432"
  volumes:
    - ./:/src
#    - ./postgres/agensgraph/:/home/agens/AgensGraph/data
  # dummy entry point to keep container running
  command: tail -f /dev/null

development:
  image: python:3.7
  volumes:
    - ./:/src
  links:
    - database
    - agensgraph
  # dummy entry point to keep container running
  command: tail -f /dev/null
