# the database
database:
  # image: postgres:9.6.5-alpine
  build:
    ./postgres/docker
  expose:
    - 5432
  ports:
   - "5432:5432"
  environment:
    POSTGRES_PASSWORD: password
  volumes:
    - ./:/src
    - ./postgres/data/:/var/lib/postgresql/data/


development:
  image: python:3.7
  volumes:
    - ./:/src
  links:
    - database
  # dummy entry point to keep container running
  command: tail -f /dev/null
