
class: sifter
outdir: ../../output/msigdb
name: msigdb

config:
  xmlPath: ../../source/msigdb/msigdb_v7.5.1.xml
  schema: ../../schema
  gene2ensembl: ../../source/ensembl/gene2ensembl.translate.link.json.gz

inputs:
  loader:
    xmlLoad:
      input: "{{config.xmlPath}}"

pipelines:
  transform:
    - from: loader
    - fieldProcess:
        field: MSIGDB
    - fieldProcess:
        field: GENESET
    - emit:
        name: raw
    - project:
        mapping:
          project_id: Reference
        rename:
          "-STANDARD_NAME": standard_name
          "-HISTORICAL_NAMES": historical_names
          "-GEOID": geoid
          "-EXACT_SOURCE": exact_source
          "-GENESET_LISTING_URL": geneset_listing_url
          "-EXTERNAL_DETAILS_URL": external_details_url
          "-CHIP": chip
          "-CATEGORY_CODE": category_code
          "-SUB_CATEGORY_CODE": sub_category_code
          "-CONTRIBUTOR": contributor
          "-CONTRIBUTOR_ORG": contributor_org
          "-DESCRIPTION_BRIEF": description_brief
          "-DESCRIPTION_FULL": description_full
          "-SYSTEMATIC_NAME": submitter_id
          "-MEMBERS_EZID": genes
          PMID: publications

    - split:
        field: genes
        sep: ","

    - lookup:
        json:
          input: "{{config.gene2ensembl}}"
          key: GeneID
          value: Ensembl_gene_identifier
        replace: genes

    - map:
        method: fix
        gpython: |
          def fix(row):
            row['genes'] = list( {"id":i} for i in row['genes'] )
            return row

    - emit:
        name: record

  object:
    - from: transform
    - objectValidate:
        title: GeneSet
        schema: "{{config.schema}}"
    - emit:
        name: gene_set
