name: coderdata
outdir: ./out

config:
  schema: ../schema
  dir: ../../source/coderdata

inputs:
  substanceReader:
    tableLoad:
      input: "{{config.dir}}/bm_drugs.csv"

pipelines:
  substance:
    - from: substanceReader
    - map:
        method: build_substance
        gpython:
          $ref: coderdata_transform.py
    - objectValidate:
        schema: '{{config.schema}}'
        title: Substance
    - emit:
        name: substance
