
name: mondo
output: ../../mondo

config:
  mondo:
    type: File
    default: ../../source/mondo/mondo.json
  schema:
    type: Dir
    default: ../../src/bmeg/bmeg-dictionary/gdcdictionary/schemas/

inputs:
  mondoJson:
    jsonLoad:
        input: "{{config.mondo}}"
        multiline: true

pipelines:
  extractGraph:
    - from: mondoJson
    - fieldProcess:
        field: graphs

  extractNodes:
    - from: extractGraph
    - fieldProcess:
        field: nodes
    - emit:
        name: nodes

  extractEdges:
    - from: extractGraph
    - fieldProcess:
        field: edges
    - emit:
        name: edges
