
class: sifter

name: mondo
outdir: ../../output/mondo

config:
  mondo: ../../source/mondo/mondo.json
  schema: ../../schema

inputs:
  mondoJson:
    jsonLoad:
        input: "{{config.mondo}}"
        multiline: true

pipelines:
  extractGraph:
    - from: mondoJson
    - fieldProcess:
        field: graphs

  extractNodes:
    - from: extractGraph
    - fieldProcess:
        field: nodes
    - emit:
        name: nodes

  extractEdges:
    - from: extractGraph
    - fieldProcess:
        field: edges
    - emit:
        name: edges
