
class: sifter

name: mondo
outdir: ../../output/mondo

config:
  mondo: ../../source/mondo/mondo.json
  schema: ../../schema

inputs:
  mondoJson:
    jsonLoad:
        input: "{{config.mondo}}"
        multiline: true

pipelines:
  extract:
    - from: mondoJson
    - fieldProcess:
        field: graphs
    - fieldProcess:
        field: nodes
    - map:
        method: fix
        gpython: |
          def fix(row):
            row["submitter_id"] = row["id"]
            row["term_id"] = row["id"].replace("http://purl.obolibrary.org/obo/", "")
            row["term"] = row.get("lbl", "")
            row["description"] = row.get("meta", {}).get("definition", {}).get("val", "")
            return row

    - project:
        mapping:
          project_id: Reference

    - objectValidate:
        schema: "{{config.schema}}"
        title: Phenotype
    - emit:
        name: phenotype
