
class: lathe
name: pharmacoTableGenerate

scripts:
  pharmacodb:
    commandLine: ./drug_response_tsv.R -o ../../table/pharmacodb_profiles.tsv -s ../../source/pharmacodb
    outputs:
      - ../../table/pharmacodb_profiles.tsv

