
class: lathe
name: pharmacoTableGenerate

dockerImages:
  - name: pharmaco-gx:4.3.0
    dir: ./

scripts:

  pharmacodb:
    docker:
      image: pharmaco-gx:4.3.0
    commandLine: "Rscript ./drug_response_tsv.R --out={{outputs.profile}} --source={{inputs.source}}"
    inputs:
      source: ../../source/pharmacodb
    outputs:
      profile: ../tables/pharmacodb_profiles.tsv
 
