
name: pharmacodb

inputs:
  sql:
    type: File
    default: ../../sources/pharmacodb/pharmacodb-1.1.1.sql

sources:
  database:
    sqldumpLoad:
      input: "{{inputs.sql}}"
      tables:
        - cells
        - cell_tissues
        - dose_responses
        - drugs
        - drug_annots
        - experiments
        - profiles
        - cellosaurus
        - source_cell_names
        - dataset_cells
        - datasets
        - source_drug_names
        - source_statistics
        - source_tissue_names
        - sources
        - tissues

sinks:
  cellTSV:
    tableWrite:
      output: cells.tsv.gz
      columns:
        - cell_id
        - accession_id
        - cell_name
        - tissue_id


links:
  cells: database
  datasets: database
  cell_tissues: database
  cellTSV: cells

pipelines:
  cells:
    - filter:
        field: table
        match: cells
    - fieldProcess:
        field: data

  cell_tissues:
    - filter:
        field: table
        match: cell_tissues
    - fieldProcess:
        field: data

  datasets:
    - filter:
        field: table
        match: datasets
    - fieldProcess:
        field: data
