
name: pharmacodb

inputs:
  sql:
    type: File
    default: ../../sources/pharmacodb/pharmacodb-1.1.1.sql

sources:
  database:
    sqldumpLoad:
      input: "{{inputs.sql}}"
      tables:
        - cells
        - cell_tissues
        - dose_responses
        - drugs
        - drug_annots
        - experiments
        - profiles
        - cellosaurus
        - source_cell_names
        - dataset_cells
        - datasets
        - source_drug_names
        - source_statistics
        - source_tissue_names
        - sources
        - tissues

links:
  cells: database

pipelines:
  cells:
    - debug: {}
    - tableWrite:
        output: cells.tsv.gz
        columns:
          - cell_id
          - accession_id
          - cell_name
          - tissue_id
  cell_tissues:
    - tableWrite:
        output: cell_tissues.tsv.gz
        columns:
          - id
          - cell_id
          - tissue_id
  dose_responses:
    - tableWrite:
        output: dose_responses.tsv.gz
        columns:
          - id
          - experiment_id
          - dose
          - response
  drugs:
    - tableWrite:
        output: drugs.tsv.gz
        columns:
          - drug_id
          - drug_name
  drug_annots:
    - tableWrite:
        output: drug_annots.tsv.gz
        columns:
          - drug_id
          - smiles
          - inchikey
          - pubchem
  experiments:
    - tableWrite:
        output: experiments.tsv.gz
        columns:
          - experiment_id
          - cell_id
          - drug_id
          - dataset_id
          - tissue_id
  profiles:
    - tableWrite:
        output: profiles.tsv.gz
        columns:
          - experiment_id
          - HS
          - Einf
          - EC50
          - AAC
          - IC50
          - DSS1
          - DSS2
          - DSS3
  cellosaurus:
    - tableWrite:
        output: cellosaurus.tsv.gz
        columns:
          - id
          - identifier
          - accession
          - as
          - sy
          - dr
          - rx
          - ww
          - cc
          - st
          - di
          - ox
          - hi
          - oi
          - sx
          - ca
          - created_at
          - updated_at
  source_cell_names:
    - tableWrite:
        output: source_cell_names.tsv.gz
        columns:
          - id
          - cell_id
          - source_id
          - cell_name
  dataset_cells:
    - tableWrite:
        output: dataset_cells.tsv.gz
        columns:
          - id
          - dataset_id
          - cell_id
  datasets:
    - tableWrite:
        output: datasets.tsv.gz
        columns:
          - dataset_id
          - dataset_name
  source_drug_names:
    - tableWrite:
        output: source_drug_names.tsv.gz
        columns:
          - id
          - drug_id
          - source_id
          - drug_name
  source_statistics:
    - tableWrite:
        output: source_statistics.tsv.gz
        columns:
          - id
          - dataset_id
          - cell_lines
          - tissues
          - drugs
          - experiments
  source_tissue_names:
    - tableWrite:
        output: source_tissue_names.tsv.gz
        columns:
          - id
          - tissue_id
          - source_id
          - tissue_name
  sources:
    - tableWrite:
        output: sources.tsv.gz
        columns:
          - source_id
          - dataset_id
          - source_name
  tissues:
    - tableWrite:
        output: tissues.tsv.gz
        columns:
          - tissue_id
          - tissue_name
