
class: lathe
name: pharmacoTableGenerate

scripts:
  pharmacodb:
    commandLine: "docker run -u `id -u` -v `cd ../.. && pwd`:/usr/src/local Rscript {{inputs.script}} --out=local/transform/pharmacodb/{{outputs.profile}} --source=local/transform/pharmacodb/{{inputs.source}}"
    inputs:
      script: ./drug_response_tsv.R
      source: ../../source/pharmacodb
    outputs:
      profile: ../../tables/pharmacodb_profiles.tsv

