
class: sifter
name: pharmacodb

outdir: ../../source/pharmacodb/tables

config:
  sql: ../../source/pharmacodb/pharmacodb-1.1.1.sql

inputs:
  database:
    sqldumpLoad:
      input: "{{config.sql}}"
      tables:
        - cells
        - cell_tissues
        - dose_responses
        - drugs
        - gene_drugs
        - drug_annots
        - experiments
        - profiles
        - cellosaurus
        - source_cell_names
        - dataset_cells
        - datasets
        - source_drug_names
        - source_statistics
        - source_tissue_names
        - sources
        - tissues

outputs:
  cells_tsv:
    tableWrite:
      from: cells
      output: cells.tsv.gz
      columns:
        - cell_id
        - accession_id
        - cell_name
        - tissue_id

  cell_tissues_tsv:
    tableWrite:
      from: cell_tissues
      output: cell_tissues.tsv.gz
      columns:
        - id
        - cell_id
        - tissue_id

  dose_responses_tsv:
    tableWrite:
      from: dose_responses
      output: dose_responses.tsv.gz
      columns:
        - id
        - experiment_id
        - dose
        - response

  gene_drugs_tsv:
    tableWrite:
      from: gene_drugs
      output: gene_drugs.tsv.gz
      columns:
        - gene_id
        - drug_id
        - estimate
        - se
        - "n"
        - tstat
        - fstat
        - pvalue
        - df
        - dataset_id
        - id

  drugs_tsv:
    tableWrite:
      from: drugs
      output: drugs.tsv.gz
      columns:
        - drug_id
        - drug_name

  drug_annots_tsv:
    tableWrite:
      from: drug_annots
      output: drug_annots.tsv.gz
      columns:
        - drug_id
        - smiles
        - inchikey
        - pubchem

  experiments_tsv:
    tableWrite:
      from: experiments
      output: experiments.tsv.gz
      columns:
        - experiment_id
        - cell_id
        - drug_id
        - dataset_id
        - tissue_id

  profiles_tsv:
    tableWrite:
      from: profiles
      output: profiles.tsv.gz
      columns:
        - experiment_id
        - HS
        - Einf
        - EC50
        - AAC
        - IC50
        - DSS1
        - DSS2
        - DSS3

  cellosaurus_tsv:
    tableWrite:
      from: cellosaurus
      output: cellosaurus.tsv.gz
      columns:
        - id
        - identifier
        - accession
        - as
        - sy
        - dr
        - rx
        - ww
        - cc
        - st
        - di
        - ox
        - hi
        - oi
        - sx
        - ca
        - created_at
        - updated_at

  source_cell_names_tsv:
    tableWrite:
      from: source_cell_names
      output: source_cell_names.tsv.gz
      columns:
        - id
        - cell_id
        - source_id
        - cell_name

  dataset_cells_tsv:
    tableWrite:
      from: dataset_cells
      output: dataset_cells.tsv.gz
      columns:
        - id
        - dataset_id
        - cell_id

  datasets_tsv:
    tableWrite:
      from: datasets
      output: datasets.tsv.gz
      columns:
        - dataset_id
        - dataset_name

  source_drug_names_tsv:
    tableWrite:
      from: source_drug_names
      output: source_drug_names.tsv.gz
      columns:
        - id
        - drug_id
        - source_id
        - drug_name

  sources_tsv:
    tableWrite:
      from: sources
      output: sources.tsv.gz
      columns:
        - source_id
        - dataset_id
        - source_name

  source_statistics_tsv:
    tableWrite:
      from: source_statistics
      output: source_statistics.tsv.gz
      columns:
        - id
        - dataset_id
        - cell_lines
        - tissues
        - drugs
        - experiments

  source_tissue_names_tsv:
    tableWrite:
      from: source_tissue_names
      output: source_tissue_names.tsv.gz
      columns:
        - id
        - tissue_id
        - source_id
        - tissue_name

  tissues_tsv:
    tableWrite:
      from: tissues
      output: tissues.tsv.gz
      columns:
        - tissue_id
        - tissue_name

pipelines:
  cells:
    - from: database
    - filter:
        field: table
        match: cells
    - fieldProcess:
        field: data

  cell_tissues:
    - from: database
    - filter:
        field: table
        match: cell_tissues
    - fieldProcess:
        field: data

  dose_responses:
    - from: database
    - filter:
        field: table
        match: dose_responses
    - fieldProcess:
        field: data

  drugs:
    - from: database
    - filter:
        field: table
        match: drugs
    - fieldProcess:
        field: data

  gene_drugs:
    - from: database
    - filter:
        field: table
        match: gene_drugs
    - fieldProcess:
        field: data

  drug_annots:
    - from: database
    - filter:
        field: table
        match: drug_annots
    - fieldProcess:
        field: data

  experiments:
    - from: database
    - filter:
        field: table
        match: experiments
    - fieldProcess:
        field: data

  profiles:
    - from: database
    - filter:
        field: table
        match: profiles
    - fieldProcess:
        field: data

  cellosaurus:
    - from: database
    - filter:
        field: table
        match: cellosaurus
    - fieldProcess:
        field: data

  source_cell_names:
    - from: database
    - filter:
        field: table
        match: source_cell_names
    - fieldProcess:
        field: data

  dataset_cells:
    - from: database
    - filter:
        field: table
        match: dataset_cells
    - fieldProcess:
        field: data

  datasets:
    - from: database
    - filter:
        field: table
        match: datasets
    - fieldProcess:
        field: data

  source_drug_names:
    - from: database
    - filter:
        field: table
        match: source_drug_names
    - fieldProcess:
        field: data

  source_statistics:
    - from: database
    - filter:
        field: table
        match: source_statistics
    - fieldProcess:
        field: data

  source_tissue_names:
    - from: database
    - filter:
        field: table
        match: source_tissue_names
    - fieldProcess:
        field: data

  sources:
    - from: database
    - filter:
        field: table
        match: sources
    - fieldProcess:
        field: data

  tissues:
    - from: database
    - filter:
        field: table
        match: tissues
    - fieldProcess:
        field: data
