
class: sifter
name: pharmacodb

outdir: ../../tables/pharmacodb

config:
  sql: ../../source/pharmacodb/pharmacodb-1.1.1.sql

inputs:
  database:
    sqldumpLoad:
      input: "{{config.sql}}"
      tables:
        - cells
        - cell_tissues
        - dose_responses
        - drugs
        - gene_drugs
        - drug_annots
        - experiments
        - profiles
        - cellosaurus
        - source_cell_names
        - dataset_cells
        - datasets
        - source_drug_names
        - source_statistics
        - source_tissue_names
        - sources
        - tissues

pipelines:
  cells:
    - from: database
    - filter:
        field: table
        match: cells
    - fieldProcess:
        field: data
    - tableWrite:
        output: cells.tsv.gz
        columns:
          - cell_id
          - accession_id
          - cell_name
          - tissue_id

  cell_tissues:
    - from: database
    - filter:
        field: table
        match: cell_tissues
    - fieldProcess:
        field: data
    - tableWrite:
        output: cell_tissues.tsv.gz
        columns:
          - id
          - cell_id
          - tissue_id

  dose_responses:
    - from: database
    - filter:
        field: table
        match: dose_responses
    - fieldProcess:
        field: data
    - tableWrite:
        output: dose_responses.tsv.gz
        columns:
          - id
          - experiment_id
          - dose
          - response

  drugs:
    - from: database
    - filter:
        field: table
        match: drugs
    - fieldProcess:
        field: data
    - tableWrite:
        output: drugs.tsv.gz
        columns:
          - drug_id
          - drug_name

  gene_drugs:
    - from: database
    - filter:
        field: table
        match: gene_drugs
    - fieldProcess:
        field: data
    - tableWrite:
        output: gene_drugs.tsv.gz
        columns:
          - gene_id
          - drug_id
          - estimate
          - se
          - "n"
          - tstat
          - fstat
          - pvalue
          - df
          - dataset_id
          - id

  drug_annots:
    - from: database
    - filter:
        field: table
        match: drug_annots
    - fieldProcess:
        field: data
    - tableWrite:
        output: drug_annots.tsv.gz
        columns:
          - drug_id
          - smiles
          - inchikey
          - pubchem

  experiments:
    - from: database
    - filter:
        field: table
        match: experiments
    - fieldProcess:
        field: data
    - tableWrite:
        output: experiments.tsv.gz
        columns:
          - experiment_id
          - cell_id
          - drug_id
          - dataset_id
          - tissue_id

  profiles:
    - from: database
    - filter:
        field: table
        match: profiles
    - fieldProcess:
        field: data
    - tableWrite:
        output: profiles.tsv.gz
        columns:
          - experiment_id
          - HS
          - Einf
          - EC50
          - AAC
          - IC50
          - DSS1
          - DSS2
          - DSS3

  cellosaurus:
    - from: database
    - filter:
        field: table
        match: cellosaurus
    - fieldProcess:
        field: data
    - tableWrite:
        output: cellosaurus.tsv.gz
        columns:
          - id
          - identifier
          - accession
          - as
          - sy
          - dr
          - rx
          - ww
          - cc
          - st
          - di
          - ox
          - hi
          - oi
          - sx
          - ca
          - created_at
          - updated_at

  source_cell_names:
    - from: database
    - filter:
        field: table
        match: source_cell_names
    - fieldProcess:
        field: data
    - tableWrite:
        output: source_cell_names.tsv.gz
        columns:
          - id
          - cell_id
          - source_id
          - cell_name

  dataset_cells:
    - from: database
    - filter:
        field: table
        match: dataset_cells
    - fieldProcess:
        field: data
    - tableWrite:
        output: dataset_cells.tsv.gz
        columns:
          - id
          - dataset_id
          - cell_id

  datasets:
    - from: database
    - filter:
        field: table
        match: datasets
    - fieldProcess:
        field: data
    - tableWrite:
        output: datasets.tsv.gz
        columns:
          - dataset_id
          - dataset_name

  source_drug_names:
    - from: database
    - filter:
        field: table
        match: source_drug_names
    - fieldProcess:
        field: data
    - tableWrite:
        output: source_drug_names.tsv.gz
        columns:
          - id
          - drug_id
          - source_id
          - drug_name

  source_statistics:
    - from: database
    - filter:
        field: table
        match: source_statistics
    - fieldProcess:
        field: data
    - tableWrite:
        output: source_statistics.tsv.gz
        columns:
          - id
          - dataset_id
          - cell_lines
          - tissues
          - drugs
          - experiments

  source_tissue_names:
    - from: database
    - filter:
        field: table
        match: source_tissue_names
    - fieldProcess:
        field: data
    - tableWrite:
        output: source_tissue_names.tsv.gz
        columns:
          - id
          - tissue_id
          - source_id
          - tissue_name

  sources:
    - from: database
    - filter:
        field: table
        match: sources
    - fieldProcess:
        field: data
    - tableWrite:
        output: sources.tsv.gz
        columns:
          - source_id
          - dataset_id
          - source_name

  tissues:
    - from: database
    - filter:
        field: table
        match: tissues
    - fieldProcess:
        field: data
    - tableWrite:
        output: tissues.tsv.gz
        columns:
          - tissue_id
          - tissue_name
