
class: lathe
name: pharmacoTableGenerate

scripts:
  pharmacodb:
    commandLine: "{{inputs.script}} -o {{outputs.profile}} -s {{inputs.source}}"
    inputs:
      script: ./drug_response_tsv.R
      source: ../../source/pharmacodb
    outputs:
      profile: ../../tables/pharmacodb_profiles.tsv

