

pipelines:
  projectGraph:
    - graphMap:
        idPrefix: Project
        idField: submitter_id
        label: Project
        class: project
        fields:
          compounds:
            toPrefix: Compound
            idTemplate: "{{row._from}}--{{row._label}}--{{row._to}}"

  caseGraph:
    - graphMap:
        idPrefix: Case
        idField: submitter_id
        label: Case
        class: case
        fields:
          projects:
            toPrefix: Project
            idTemplate: "{{row._from}}--{{row._label}}--{{row._to}}"

  sampleGraph:
    - graphMap:
        idPrefix: Sample
        idField: submitter_id
        label: Sample
        class: sample
        fields:
          case:
            toPrefix: "Case"
            idTemplate: "{{row._from}}--{{row._label}}--{{row._to}}"

  aliquotGraph:
    - graphMap:
        idPrefix: Aliquot
        idField: submitter_id
        label: Aliquot
        class: aliquot
        fields:
          sample:
            toPrefix: Sample
            idTemplate: "{{row._from}}--{{row._label}}--{{row._to}}"

  drGraph:
    - graphMap:
        idPrefix: DrugResponse
        idField: submitter_id
        label: DrugResponse
        class: drug_response
        fields:
          compounds:
            toPrefix: Compound
            idTemplate: "{{row._from}}--{{row._label}}--{{row._to}}"
          aliquot:
            toPrefix: Aliquot
            idTemplate: "{{row._from}}--{{row._label}}--{{row._to}}"
