
class: sifter

outdir: ../../output/pharmacodb/
name: pharmacodb_profiles_gx

config:
  treatmentResponseDir: ../../source/pharmacodb/
  treatmentSynonymsFile: ../../tables/pharmacodb_treatment.utable.final.json.gz
  synonymsFile: ../../tables/chemblSynonyms.longTable.synonyms.json.gz
  schema: ../../schema/

inputs:
  profileReader:
    #plugin:
    #  commandline: "../../util/chembl-matchup.py -t {{config.treatmentSynonymsFile}} -c {{config.synonymsFile}} {{config.treatmentResponseDir}}/CTRPv2_2015/response.tsv"
    tableLoad:
      input: "{{config.treatmentResponseDir}}/CTRPv2_2015/response.tsv"
pipelines:
  transform:
    - from: profileReader
    - emit:
        name: debug1
    - map:
        method: cleanEmptyFields
        gpython:
          $ref: clean.py
    - filter:
        field: treatmentid
        check: 
    - emit:
        name: debug2
    - filter:
        field: sampleid
        check:
    - map:
        method: cleanDoseViability
        gpython:
          $ref: clean.py
#    - map:
#        method: finalclean
#        gpython: |
 
  drug_response:
    - from: transform
    - objectValidate:
        title: DrugResponse
        schema: "{{config.schema}}"
    - emit:
        name: DrugResponse
   
