
class: sifter

name: dr_reduce
outdir: ../../output/pharmacodb/

config:
  doseResponsePath:
    type: File
    default: ../../output/pharmacodb/dose_responses.tsv.gz

inputs:
  doseResponseFile:
    tableLoad:
      input: "{{config.doseResponsePath}}"

pipelines:
  curveReduce:
    - from: doseResponseFile
    - reduce:
        field: experiment_id
        method: merge
        init: { "curve" : {} }
        gpython: |

          def merge(x,y):
            y["curve"][x["dose"]] = x["response"]
            y["experiment_id"] = x["experiment_id"]
            return y

    - emit:
        name: dose_response_curve
