
class: sifter

outdir: ../../tables/
name: pharmacodb_treatment

config:
  tableDir: ../../source/pharmacodb

inputs:
  treatmentReader:
    glob:
      input: "{{config.tableDir}}/*/treatments.tsv"
      tableLoad: {}

pipelines:
  utable:
    - from: treatmentReader
    - distinct:
        value: "{{row.UNIQUEtreatmentid}}+{{row.PROJECTtreatmentid}}"
    - emit:
        name: final
