
class: sifter
name: GDSC_VCF_Transform
outdir: ../../output/gdsc

config:
  modelTable: ../../source/gdsc/model_list_20230110.csv
  vcfBase: ../../source/gdsc/mutations_wes_vcf_20221010
  schema: ../../schema

inputs:
  vcfRead:
    glob:
      input: "{{config.vcfBase}}/*_Sanger_wes_snp_vaf.caveman_c.annot_drv.vcf.gz"
      storeFileName: _fileName
      tableLoad:
        columns:
          - CHROM
          - POS
          - ID
          - REF
          - ALT
          - QUAL
          - FILTER
          - INFO
          - FORMAT
          - NORMAL
          - TUMOR

pipelines:
  namefix:
    - from: vcfRead
    - map: 
        method: fix
        gpython: |
          def fix(row):
            row["submitter_id"] = row["_fileName"].split("_")[0]
            row["aliquot_id"] = row["_fileName"].split("_")[0]
            return row
    - lookup:
        tsv:
          input: "{{config.modelTable}}"
          key: model_id
          value: COSMIC_ID
          sep: ","
        replace: aliquot_id
    - emit:
        name: source

  variants:
    - from: namefix
    - map: 
        method: fix
        gpython: |
          def fix(row):
            k = row["FORMAT"].split(":")
            n = row["NORMAL"].split(":")
            t = row["TUMOR"].split(":")
            row["tumor"] = dict( zip(k,t) )
            row["normal"] = dict( zip(k,n) )
            return row
    - map:
        method: fix
        gpython: |
          def fix(row):
            row["t_depth"] = int(row["tumor"]["DEP"])
            row["t_ref_count"] = int(row["tumor"]["WTR"])
            row["t_alt_count"] = int(row["tumor"]["MTR"])
            row["n_depth"] = int(row["normal"]["DEP"])
            row["n_ref_count"] = int(row["normal"]["WTR"])
            row["n_alt_count"] = int(row["normal"]["MTR"])
            row["filter"] = row["FILTER"]
            row["methods"] = ["caveman"]
            row["somatic_callset"] = row["aliquot_id"]
            row["allele"] = "GRCh38:%s:%s:%s:%s" % (row["CHROM"], row["POS"], row["REF"], row["ALT"] )
            return row
    - project:
        mapping: 
          id: "{{row.somatic_callset}}-{{row.allele}}"
    - objectValidate:
        schema: "{{config.schema}}"
        title: "SomaticVariant"
    - emit:
        name: somatic_variant
  
  callset:
    - from: namefix
    - map:
        method: fix
        gpython: |
          def fix(row):
            row["id"] = row["aliquot_id"]
            #row["submitter_id"] = row["aliquot_id"]
            row["tumor_aliquot_id"] = row["aliquot_id"]
            row["project_id"] = "GDSC"
            return row
    - distinct:
        value: "{{row.id}}"
    - objectValidate:
        schema: "{{config.schema}}"
        title: "SomaticCallset"
    - emit:
        name: somatic_callset
  
  allele: 
    - from: vcfRead
    - map:
        method: fix
        gpython: |
          def fix(row):
            return {
              "id": "GRCh38:%s:%s:%s:%s" % (row["CHROM"], row["POS"], row["REF"], row["ALT"] ),
              "alternate_bases": row["ALT"],
              "reference_bases" : row["REF"],
              "chromosome":row["CHROM"], 
              "genome" : "GRCh38",
              "start": int(row["POS"])
            }
    - objectValidate:
        schema: "{{config.schema}}"
        title: "Allele"
    - emit:
        name: allele
