
class: sifter
name: pathway_commons
memMB: 20000

outdir: ../../output/pathway_commons/

config:
  extSifBase: ../../source/pathway_commons
  uniprotMap: ../../tables/uniprot2ensembl.tsv
  schema: ../../schema/

inputs:
  extSif:
    glob:
      input: "{{config.extSifBase}}/*.extSIF"
      tableLoad:
        columns:
          - SRC_ID
          - INTERACTION_TYPE
          - DST_ID
          - SOURCE
          - PUBMED
          - PATHWAY

  complex:
    glob:
      input: "{{config.extSifBase}}/*.complex"
      tableLoad:
        columns:
          - COMPLEX_ID
          - PROTEIN


pipelines:
  interactionMap:
    - from: extSif
    - project:
        mapping:
          #id: "{{row.SRC_ID}}-{{row.INTERACTION_TYPE}}-{{row.DST_ID}}"
          submitterId:  "{{row.SRC_ID}}-{{row.INTERACTION_TYPE}}-{{row.DST_ID}}"
          projectId: Reference
          interactionOutput: [ { "submitterId": "{{row.DST_ID}}", "projectId":"reference" } ]
          interactionInput: [ { "submitterId" : "{{row.SRC_ID}}", "projectId":"reference" } ]
          source: "{{row.SOURCE}}"
          type: interaction
    - map:
        method: fix
        gpython: |
          def fix(row):
            o = []
            for i in row["PUBMED"].split(","):
              o.append( {"submitterId" : "pmid/" + i, "projectId":"reference"})
            row["publications"] = o
            return row

    - objectValidate:
        title: Interaction
        schema: "{{config.schema}}"
    - emit:
        name: interaction
  
  complexBundle:
    - from: complex
    - reduce:
        field: COMPLEX_ID
        method: merge
        init: { "proteins": [] }
        gpython: |

          def merge(x,y):
            x["proteins"] = [x["PROTEIN"]] + y["proteins"]
            return x
      
    - project:
        mapping:
          #id: "{{row.COMPLEX_ID}}"
          projectId: Reference
          submitterId: "{{row.COMPLEX_ID}}"
    
    - emit:
        name: complex