class: sifter
name: gdc_fhir
outdir: ../../output/gdc_fhir


config:
  patients: ../../source/gdc_fhir/META/Patient.ndjson
  research_studies: ../../source/gdc_fhir/META/ResearchStudy.ndjson
  research_subjects: ../../source/gdc_fhir/META/ResearchSubject.ndjson
  specimens: ../../source/gdc_fhir/META/Specimen.ndjson
  procedures: ../../source/gdc_fhir/META/Procedure.ndjson
  conditions: ../../source/gdc_fhir/META/Condition.ndjson
  observations: ../../source/gdc_fhir/META/Observation.ndjson
  encounters: ../../source/gdc_fhir/META/Encounter.ndjson
  medication_administrations: ../../source/gdc_fhir/META/MedicationAdministration.ndjson
  medications: ../../source/gdc_fhir/META/Medication.ndjson
  imaging_studies: ../../source/gdc_fhir/META/ImagingStudy.ndjson
  document_references: ../../source/gdc_fhir/META/DocumentReference.ndjson
  schema: ../../schema


inputs:
  patient:
    jsonLoad:
      input: "{{config.patients}}"

  research_study:
    jsonLoad:
      input: "{{config.research_studies}}"

  research_subject:
    jsonLoad:
      input: "{{config.research_subjects}}"

  specimen:
    jsonLoad:
      input: "{{config.specimens}}"

  procedure:
    jsonLoad:
      input: "{{config.procedures}}"

  condition:
    jsonLoad:
      input: "{{config.conditions}}"

  observation:
    jsonLoad:
      input: "{{config.observations}}"

  encounter:
    jsonLoad:
      input: "{{config.encounters}}"

  medication_administration:
    jsonLoad:
      input: "{{config.medication_administrations}}"

  medication:
    jsonLoad:
      input: "{{config.medications}}"

  imaging_study:
    jsonLoad:
      input: "{{config.imaging_studies}}"

  document_reference:
    jsonLoad:
      input: "{{config.document_references}}"



pipelines:
  patientObj:
    - from: patient
    - objectValidate:
        title: Patient
        schema: "{{config.schema}}"

    - emit:
        name: Patient

  researchStudyObj:
    - from: research_study
    - objectValidate:
        title: ResearchStudy
        schema: "{{config.schema}}"

    - emit:
        name: ResearchStudy

  researchSubjectObj:
    - from: research_subject
    - objectValidate:
        title: ResearchSubject
        schema: "{{config.schema}}"

    - emit:
        name: ResearchSubject

  specimenObj:
    - from: specimen
    - objectValidate:
        title: Specimen
        schema: "{{config.schema}}"

    - emit:
        name: Specimen

  procedureObj:
    - from: procedure
    - objectValidate:
        title: Procedure
        schema: "{{config.schema}}"

    - emit:
        name: Procedure

  conditionObj:
    - from: condition
    - objectValidate:
        title: Condition
        schema: "{{config.schema}}"

    - emit:
        name: Condition

  observationObj:
    - from: observation
    - objectValidate:
        title: Observation
        schema: "{{config.schema}}"

    - emit:
        name: Observation

  encounterObj:
    - from: encounter
    - objectValidate:
        title: Encounter
        schema: "{{config.schema}}"

    - emit:
        name: Encounter

  medicationAdministrationObj:
    - from: medication_administration
    - objectValidate:
        title: MedicationAdministration
        schema: "{{config.schema}}"

    - emit:
        name: MedicationAdministration

  medicationObj:
    - from: medication
    - objectValidate:
        title: Medication
        schema: "{{config.schema}}"

    - emit:
        name: Medication

  imagingStudyObj:
    - from: imaging_study
    - objectValidate:
        title: ImagingStudy
        schema: "{{config.schema}}"

    - emit:
        name: ImagingStudy

  documentReferenceObj:
    - from: document_reference
    - objectValidate:
        title: DocumentReference
        schema: "{{config.schema}}"

    - emit:
        name: DocumentReference

