wget https://s3.pgkb.org/data/annotations.zip -O source/pharmgkb/annotations.zip
wget https://s3.pgkb.org/data/relationships.zip -O source/pharmgkb/relationships.zip
wget https://s3.pgkb.org/data/drugLabels.zip -O source/pharmgkb/drugLabels.zip
wget https://s3.pgkb.org/data/pathways-biopax.zip -O source/pharmgkb/pathways-biopax.zip
wget https://s3.pgkb.org/data/automated_annotations.zip -O source/pharmgkb/automated_annotations.zip
wget https://s3.pgkb.org/data/genes.zip -O source/pharmgkb/genes.zip
wget https://s3.pgkb.org/data/drugs.zip -O source/pharmgkb/drugs.zip
wget https://s3.pgkb.org/data/chemicals.zip -O source/pharmgkb/chemicals.zip
wget https://s3.pgkb.org/data/phenotypes.zip -O source/pharmgkb/phenotypes.zip
wget https://s3.pgkb.org/data/variants.zip -O source/pharmgkb/variants.zip
wget https://s3.pgkb.org/data/clinicalVariants.zip -O source/pharmgkb/clinicalVariants.zip
