
name: chemblGraph

outdir: ../../out-graph/chembl

inputs:
  schema:
    type: Dir
    default: ../../src/bmeg/bmeg-dictionary/gdcdictionary/schemas
  protein_drug_association:
    type: File
    default: ../../outputs/chembl/chembDrugMechanismExtract.protein_drug_association.json.gz

sources:
  jsonReader:
    input: "{{inputs.protein_drug_association}}"

pipelines:
  graphBuild:
    idPrefix: CHEMBL-MEC
    idField: submitter_id
    label: ProteinDrugAssociation
    class: protein_drug_association
    fields:
      genes:
        idTemplate: "{{row._from}}--{{row._label}}--{{row._to}}"
        toPrefix: ENSG
      publications:
        toPrefix: "Publication"
        idTemplate: "{{row._from}}--{{row._label}}--{{row._to}}"
      compound:
        toPrefix: "Compound"
        idTemplate: "{{row._from}}--{{row._label}}--{{row._to}}"
