
class: sifter

name: chemblSynonyms
outdir: ../../tables/

config:
  sqlite:  ../../source/chembl/chembl_32/chembl_32_sqlite/chembl_32.db
  schema: ../../schema/

inputs:
  sqlQuery:
    sqliteLoad:
      input: "{{config.sqlite}}"
      query: "select * from MOLECULE_DICTIONARY as a INNER JOIN MOLECULE_SYNONYMS as b on a.MOLREGNO=b.MOLREGNO"
  sqlQueryIUPAC:
    sqliteLoad:
      input: "{{config.sqlite}}"
      query: "select CHEMBL_ID,a.MOLREGNO,SYNONYMS from MOLECULE_DICTIONARY as a INNER JOIN MOLECULE_SYNONYMS as b on a.MOLREGNO=b.MOLREGNO UNION ALL select CHEMBL_ID,a.MOLREGNO,COMPOUND_NAME AS SYNONYMS from MOLECULE_DICTIONARY as a INNER JOIN COMPOUND_RECORDS as c on a.MOLREGNO=c.MOLREGNO"

pipelines:
  buildTable:
    - from: sqlQuery
    - accumulate:
        field: molregno
        dest: recs
    - map:
        method: fix
        gpython: |
          def fix(row):
            s = []
            for i in row["recs"]:
              s.append(i["synonyms"])
            row["synonyms"] = s
            return row
    - project:
        mapping:
          id: "{{row.molregno}}"
    - clean: 
        fields:
          - id
          - synonyms
    - emit:
        name: synonyms
  longTable:
    - from: sqlQueryIUPAC
    - project:
        mapping:
          id: "{{row.chembl_id}}"
    - clean:
        fields:
          - id
          - synonyms
    - distinct:
        value: "{{row.synonyms}}"
    - emit:
        name: synonyms
