
class: sifter

name: chemblSynonyms
outdir: ../../tables/

config:
  sqlite:  ../../source/chembl/chembl_31/chembl_31_sqlite/chembl_31.db
  schema: ../../schema/

inputs:
  sqlQuery:
    sqliteLoad:
      input: "{{config.sqlite}}"
      query:  "select * from MOLECULE_SYNONYMS order by MOLREGNO"

pipelines:
  buildTable:
    - from: sqlQuery
    - accumulate:
        field: molregno
        dest: recs
    - map:
        method: fix
        gpython: |
          def fix(row):
            s = []
            for i in row["recs"]:
              s.append(i["synonyms"])
            row["synonyms"] = s
            return row
    - project:
        mapping:
          id: "{{row.molregno}}"
    - clean: 
        fields:
          - id
          - synonyms
    - emit:
        name: synonyms