
class: sifter
name: GTEX_Gene_Expression
outdir: ../../output/gtex
memMB: 50000

config:
  gctFile: ../../source/gtex/GTEx_Analysis_2017-06-05_v8_RNASeQCv1.1.9_gene_tpm.gct.gz
  schema: ../../schema

inputs:
  geneRead:
    transposeLoad:
      input: "{{config.gctFile}}"
      #onDisk: true
      rowSkip: 2


pipelines:
  gctProcess:
    - from: geneRead
    - map:
        method: nodeMap
        gpython: |
           
           def nodeMap(x):
             values = {}
             for k, v in x.items():
               if k != "Name" and k != "Description":
                j = k.split(".")[0]
                try:
                  values[j] = float(v)
                except ValueError:
                  pass
                  
             return {
               "id" : x["Name"],
               "submitter_id" : x["Name"],
               "project_id" : "GTEX",
               "metric" : "TPM_GENE",
               "method" : "Illumina HiSeq",
               "values": values
             }
    - objectValidate:
        title: GeneExpression
        schema: "{{config.schema}}"
    - emit:
        name: gene_expression