
class: sifter

name: pubmed
outdir: ../../output/pubmed
memMB: 64000

config:
  baseline: ../../source/pubmed/baseline
  schema: ../../schema

inputs:
  pubmedRead:
    glob:
      parallelize: true
      input: "{{config.baseline}}/*.xml.gz"
      xmlLoad: {}


pipelines:
  transform:
    - from: pubmedRead
    - fieldProcess:
        field: PubmedArticleSet
    - fieldProcess:
        field: PubmedArticle
    - map:
        method: update
        gpython: 
          $ref: fix.py

    - project:
        mapping:
          submitter_id: "{{row.pmid}}"
          url: "https://www.ncbi.nlm.nih.gov/pubmed/{{row.pmid}}"
          project_id: Reference
          id: "pmid/{{row.pmid}}"

    - objectValidate:
        title: Publication
        schema: "{{config.schema}}"

    - emit:
        name: publication
