##################
### ENSEMBL

class: Workflow
cwlVersion: v1.0


$namespaces:
  bmeg: http://bmeg.io

inputs:
  GFF_GZ:
    type: File
    bmeg:key: source/ensembl.gtf.gz

steps:

  ensembl-transform:
    run: ../transform/ensembl/ensembl-transform.cwl
    in:
      GFF_GZ: GFF_GZ
    out:
      - TRANSCRIPT
      - GENE
      - EXON

outputs:
  TRANSCRIPT:
    type: File
    outputSource: ensembl-transform/TRANSCRIPT
    bmeg:key: biostream/ensembl/ensembl.Transcript.json
  GENE:
    type: File
    outputSource: ensembl-transform/GENE
    bmeg:key: biostream/ensembl/ensembl.Gene.json
  EXON:
    type: File
    outputSource: ensembl-transform/EXON
    bmeg:key: biostream/ensembl/ensembl.Exon.json
