##################
### GTEX

class: Workflow
cwlVersion: v1.0


$namespaces:
  bmeg: http://bmeg.io

inputs:
  GTEX_MATRIX:
    type: File
    bmeg:key: source/gtex_Kallisto_tpm.gz
    bmeg:url: https://toil.xenahubs.net/download/gtex_Kallisto_tpm.gz

steps:
  gtex-transform:
    run: ../transform/rna-matrix/transform-rna-matrix.cwl
    in:
      matrix: GTEX_MATRIX
    out:
      - GeneExpression
      - ExpressionOf

outputs:
  GeneExpression:
    type: File
    outputSource: gtex-transform/GeneExpression
    bmeg:key: biostream/gtex/gtex.GeneExpression.vertex.json
  ExpressionOf:
    type: File
    outputSource: gtex-transform/ExpressionOf
    bmeg:key: biostream/gtex/gtex.ExpressionOf.edge.json
