


class: sifter
name: depmap-expression
outdir: ../../output/depmap/

config:
  geneTable: ../../source/ensembl/gene2ensembl.translate.link.json.gz
  expressionFile: ../../source/depmap/OmicsExpressionProteinCodingGenesTPMLogp1.csv
  schema: ../../schema/

inputs:
  expression:
    tableLoad:
      input: "{{config.expressionFile}}"
      sep: ","

pipelines:
  values:
    - from: expression
    - map:
        method: fix
        gpython: |

          def fix(row):
            values = {}
            sub_id = ""
            for k, v in row.items():
              if k == "":
                sub_id = v
              else:
                t = k.split(" ")[1].replace("(", "").replace(")", "")
                values[t] = float(v)
            return {
              "submitter_id" : sub_id,
              "project_id" : "Depmap",
              "metric" : "GENE_TPM",
              "method" : "Illumina HiSeq",
              "values": values
            }
    - lookup:
        replace: values
        json:
          input: "{{config.geneTable}}"
          key: GeneID
          value: Ensembl_gene_identifier
    - objectValidate:
        class: gene_expression
        schema: "{{config.schema}}"
    - emit:
        name: expression