
class: sifter
name: go_gaf
outdir: ../../output/go/

config:
  gafFile:
    type: File
    default: ../../source/go/goa_human.gaf.gz

inputs:
  gafLoad:
    tableLoad:
      input: "{{config.gafFile}}"
      #comment: "!"
      columns:
        - db
        - id
        - symbol
        - qualifier
        - goID
        - reference
        - evidenceCode
        - from
        - aspect
        - name
        - synonym
        - objectType
        - taxon
        - date
        - assignedBy
        - extension
        - geneProduct

pipelines:
  dump:
    - from: gafLoad
    - emit:
        name: gaf
