
name: goJson
class: sifter

outdir: ../../output/go/

config:
  obo: ../../source/go/go.json
  schema: ../../src/bmeg/bmeg-dictionary/gdcdictionary/schemas/

inputs:
  oboJson:
    jsonLoad:
      input: "{{config.obo}}"
      multiline: true

pipelines:
  recordOpen:
    - from: oboJson
    - fieldProcess:
        field: graphs

  nodeOpen:
    - from: recordOpen
    - fieldProcess:
        field: nodes
    - project:
        mapping:
          submitter_id: "{{row.id}}"
          project_id: reference
          go_id: "{{row.id}}"
          name: "{{row.lbl}}"
          namespace: "{{row.type}}"
    - map:
        method: syn
        gpython: |

          def syn(rec):
            synonym = []
            if 'synonyms' in rec:
                for i in rec['synonyms']:
                    synonym.append(i['val'])
            rec['synonym'] = synonym
            rec['definition'] = ""
            rec['xref'] = ""
            if "meta" in rec:
              if "definition" in rec['meta']:
                rec['definition'] = rec['meta']['definition']['val']
                rec['xref'] = rec['meta']['definition']['xrefs']
            return rec

    - emit:
        name: before

    - objectValidate:
        class: gene_ontology_term
        schema: "{{config.schema}}"

    - emit:
        name: term

  edgeOpen:
    - from: recordOpen
    - fieldProcess:
        field: edges
    - emit:
        name: edges
