
name: goReduce
class: sifter

outdir: ../../output/go/

config:
  edges: ../../output/go/go.edgeOpen.edges.json.gz

inputs:
  edgeJson:
    jsonLoad:
      input: "{{inputs.edges}}"


pipelines:
  edgeReduce:
    - from: edgeJson
    - reduce:
        init: { "is_a" : [] }
        field: sub
        method: merge
        gpython: |
          def merge(x,y):
            if x['pred'] == "is_a":
              y["is_a"].append( x["obj"] )
            y["sub"] = x["sub"]
            return y
    - emit:
        name: edge_reduce
