
class: sifter

name: ensembl
outdir: ../../output/ensembl

config:
  gffPath: ../../source/ensembl/Homo_sapiens.GRCh37.87.chr_patch_hapl_scaff.gff3.gz
  genomeBuild: GRCh37
  schema: ../../src/bmeg/bmeg-dictionary/gdcdictionary/schemas/

inputs:
  gff:
    tableLoad:
      input: "{{config.gffPath}}"
      columns:
        - seqID
        - source
        - feature
        - start
        - end
        - score
        - strand
        - phase
        - attributes

pipelines:
  transform:
    - from: gff
    - fieldParse:
        field: attributes
        sep: ";"
        assign: "="

  transcripts:
    - from: transform
    - filter:
        field: feature
        match: transcript
    - project:
        mapping:
          feature_id: "{{row.attributes.transcript_id}}"
          biotype: "{{row.type}}"
          submitter_id: "{{row.attributes.transcript_id}}"
          transcript_id: "{{row.attributes.transcript_id}}"
          project_id: "Reference"
          chromosome: "{{row.seqID}}"
          genome: "{{config.genomeBuild}}"
          gene: "{{row.attributes.Parent}}"
    - regexReplace:
        field: gene
        regex: "^gene:"
        replace: ""
    - objectCreate:
        schema: "{{config.schema}}"
        class: transcript
    - emit:
        name: transcript

  exons:
    - from: transform
    - filter:
        field: feature
        match: exon
    - project:
        mapping:
          feature_id: "{{row.attributes.exon_id}}"
          biotype: "{{row.type}}"
          submitter_id: "{{row.attributes.exon_id}}"
          exon_id: "{{row.attributes.exon_id}}"
          project_id: "Reference"
          chromosome: "{{row.seqID}}"
          genome: "{{config.genomeBuild}}"
          transcripts: "{{row.attributes.Parent}}"
    - regexReplace:
        field: transcripts
        regex: "^transcript:"
        replace: ""
    - objectCreate:
        schema: "{{config.schema}}"
        class: exon
    - emit:
        name: exon

  genes:
    - from: transform
    - filter:
        field: feature
        match: gene
    - project:
        mapping:
          feature_id: "{{row.attributes.gene_id}}"
          biotype: "{{row.type}}"
          submitter_id: "{{row.attributes.gene_id}}"
          gene_id: "{{row.attributes.gene_id}}"
          project_id: "Reference"
          chromosome: "{{row.seqID}}"
          genome: "{{config.genomeBuild}}"
          description: "{{row.attributes.description}}"
          symbol: "{{row.attributes.Name}}"
    - objectCreate:
        schema: "{{config.schema}}"
        class: gene
    - emit:
        name: gene
