class: sifter

name: gene2ensembl

outdir: ../../source/ensembl/

config:
  file: ../../source/ensembl/gene2ensembl.gz

inputs:
  geneFile:
    tableLoad:
      input: "{{config.file}}"
      columns:
        - tax_id
        - GeneID
        - Ensembl_gene_identifier
        - RNA
        - Ensembl_rna_identifier
        - protein
        - Ensembl_protein_identifier

pipelines:
  translate:
    - from: geneFile
    - filter:
        field: tax_id
        match: 9606
    - emit:
        name: link
