
class: sifter
name: hugoMapping
outdir: ../../source/ensembl

config:
  hugoPath: ../../source/hugo/hugo.tsv

inputs:
  hugoTSV:
    tableLoad:
      input: "{{config.hugoPath}}"

outputs:
  uniprot2ensembl:
    tableWrite:
      from: tableFilter
      output: "uniprotId2ensemblGene.alt.tsv"
      columns:
        - "uniprot"
        - "ensembl"

pipelines:
  tableFilter:
    - from: hugoTSV
    - project:
        rename:
          "UniProt ID(supplied by UniProt)": uniprot
          "Ensembl ID(supplied by Ensembl)": ensembl
    - filter:
        field: uniprot
        check: hasValue
    - filter:
        field: ensembl
        check: hasValue
