
name: uniprot

outdir: ../../output/ensembl

config:
  gffPath:
    type: File
    default: ../../source/ensembl/Homo_sapiens.GRCh37.85.uniprot.tsv.gz
  schema:
    type: Dir
    default: ../../src/bmeg/bmeg-dictionary/gdcdictionary/schemas/
  genomeBuild:
    default: GRCh37

inputs:
  gff:
    tableLoad:
      input: "{{config.gffPath}}"

pipelines:
  transform:
    - from: gff
    - project:
        mapping:
          protein_id: "{{row.protein_stable_id}}"
          submitter_id: "{{row.protein_stable_id}}"
          genome: "{{config.genomeBuild}}"
          project_id: Reference
    - objectCreate:
        schema: "{{config.schema}}"
        class: protein
    - emit:
        name: protein
