
class: sifter
name: uniprot

outdir: ../../output/ensembl

config:
  uniprotTSV: ../../source/ensembl/Homo_sapiens.GRCh37.85.uniprot.tsv.gz
  schema: ../../src/bmeg/bmeg-dictionary/gdcdictionary/schemas/
  genomeBuild: GRCh37

inputs:
  uniprot:
    tableLoad:
      input: "{{config.uniprotTSV}}"

pipelines:
  transform:
    - from: uniprot
    - project:
        mapping:
          protein_id: "{{row.protein_stable_id}}"
          submitter_id: "{{row.protein_stable_id}}"
          genome: "{{config.genomeBuild}}"
          project_id: Reference
          uniprot: "{{row.xref}}"
    - reduce:
        field: protein_id
        method: merge
        init: {}
        gpython: |

          def forceList(a):
            if not isinstance(a, list):
              return [a]
            return a

          def merge(x,y):
            if "uniprot" in y:
              x["uniprot"] = forceList(x["uniprot"]) + forceList(y["uniprot"])
            else:
              x["uniprot"] = forceList(x["uniprot"])
            return x

    #- debug: {}

    - objectValidate:
        schema: "{{config.schema}}"
        class: protein
    - emit:
        name: protein
