$schema: https://json-schema.org/draft/2020-12/schema
$id: Project
title: Project
type: object
description: Any specifically defined piece of work that is undertaken or attempted
  to meet a single requirement.
required:
  - submitterId
  - projectId
links:
  - rel: programs_Progr
    href: Program/{id}
    templateRequired:
      - id
    targetSchema:
      $ref: Program.yaml
    templatePointers:
      id: /programs/-/id
    targetHints:
      directionality:
        - outbound
      multiplicity:
        - has_many
      backref:
        - programs_project
properties:
  id:
    type: string
    element_property: true
  type:
    type: string
    element_property: true
  programs:
    type: array
    items:
      $ref: Program.yaml
    element_property: true
    backref: programs_project
  projectId:
    $ref: _definitions.yaml#/project_id
    element_property: true
  gdcAttributes:
    element_property: true
  submitterId:
    type: string
    element_property: true
  createdDateTime:
    $ref: _definitions.yaml#/datetime
    element_property: true
  updatedDateTime:
    $ref: _definitions.yaml#/datetime
    element_property: true
  resourceType:
    default: project
    type: string
    description: One of the resource types defined as part of BMEG
