
class: sifter
name: gdc-mafs
outdir: ../../output/gdc/open-maf

config:
  mafBase: ../../source/gdc/open-maf
  schema: ../../schema/

inputs:
  mafData:
    glob:
      input: "{{config.mafBase}}/*.maf.gz"
      storeFilename: _fileName
      tableLoad: {}

pipelines:
  scan:
    - from: mafData
    - regexReplace:
        field: Tumor_Seq_Allele2
        regex: "-"
        replace: "."
    - project:
        mapping:
          somatic_callset: "{{row.Tumor_Sample_UUID}}:{{row.Matched_Norm_Sample_UUID}}"
          allele: "{{row.NCBI_Build}}{{row.Chromosome}}:{{row.Start_Position}}:{{row.Reference_Allele}}:{{row.Tumor_Seq_Allele2}}"
          methods: "{{row.callers}}"
    - split:
        field: methods
        sep: ";"
    - fieldType:
        t_depth: int
        t_ref_count: int
        t_alt_count: int
        n_depth: int
        n_ref_count: int
        n_alt_count: int
        start: int
    - dropNull: {}
    - project:
        mapping: 
          id: "{{row.somatic_callset}}-{{row.allele}}"
    - objectValidate:
        schema: "{{config.schema}}"
        title: SomaticVariant
    - emit:
        name: variant
  
  allele:
    - from: mafData
    - regexReplace:
        field: Tumor_Seq_Allele2
        regex: "-"
        replace: "."
    - project:
        mapping:
          submitter_id: "{{row.NCBI_Build}}{{row.Chromosome}}:{{row.Start_Position}}:{{row.Reference_Allele}}:{{row.Tumor_Seq_Allele2}}"
          reference_bases: "{{row.Reference_Allele}}"
          alternate_bases: "{{row.Tumor_Seq_Allele2}}"
          genome: "{{row.NCBI_Build}}"
          chromosome: "{{row.Chromosome}}"
          start: "{{row.Start_Position}}"
          end:  "{{row.End_Position}}"
          project_id: "gdc"
    - project:
        mapping:
          id: "{{row.genome}}{{row.chromosome}}:{{row.start}}:{{row.reference_bases}}:{{row.alternate_bases}}"
    - clean:
        fields:
          - id
          - submitter_id
          - reference_bases
          - alternate_bases
          - genome
          - chromosome
          - start
          - end
          - project_id
    - fieldType:
        start: int
        end: int
    - objectValidate:
        title: Allele
        schema: "{{config.schema}}"
    - emit:
        name: allele

  somaticCallsets:
    - from: mafData
    - distinct:
        value: "{{row.Tumor_Sample_UUID}}:{{row.Matched_Norm_Sample_UUID}}"
    - project:
        mapping:
          id: "{{row.Tumor_Sample_UUID}}:{{row.Matched_Norm_Sample_UUID}}"
          submitter_id: "{{row._fileName}}"
          tumor_aliquot_id: "{{row.Tumor_Sample_UUID}}"
          normal_aliquot_id: "{{row.Matched_Norm_Sample_UUID}}"
          project_id: TBD # figure out how to get this information here
    - objectValidate:
        schema: "{{config.schema}}"
        title: SomaticCallset
    - emit: 
        name: callset