

class: sifter

name: rnaseq
outdir: ../../output/gdc


config:
  data: ../../source/gdc/rna-seq/
  schema: ../../schema

inputs:
  tsvData:
    glob:
      storeFilename: "file_name"
      input: "{{config.data}}/*.tsv"
      tableLoad: {}


pipelines:
  rna:
    - from: tsvData
    - accumulate:
        field: file_name
        dest: rows
    - map:
        method: update
        gpython: |

          def update(row):
            values = {}
            for i in row["rows"]:
              gene = i["gene_id"].split(".")[0]
              try:
                values[gene] = float(i["tpm_unstranded"])
              except ValueError:
                pass
            return {
              "id" : row["file_name"].split(".")[0],
              "submitter_id" : row["file_name"].split(".")[0],
              "project_id" : "TCGA",
              "metric" : "TPM_GENE",
              "method" : "Illumina HiSeq",
              "values" : values
            }
    - objectValidate:
        schema: "{{config.schema}}"
        title: GeneExpression

    - emit:
        name: gene_rnaseq
