
class: sifter
name: gdc
outdir: ../../output/gdc

config:
  casesJSON: ../../source/gdc/cases.json
  schema: ../../schema

inputs:
  caseData:
    jsonLoad:
      input: "{{config.casesJSON}}"

pipelines:
  caseObject:
    - from: caseData
    - project:
        mapping:
          studies: "{{row.project.project_id}}"
          experiments: "exp:{{row.project.project_id}}"
          project_id: "{{row.project.project_id}}"
          type: case
    - map:
        method: fix
        gpython: |

          def fix(x):
            samples = []
            for s in x.get('samples', []):
              samples.append({"id":s["sample_id"]})
            x['samples'] = samples
            return x

    - objectValidate:
        title: Case
        schema: "{{config.schema}}"
    - emit:
        name: case

  sampleData:
    - from: caseData
    - fieldProcess:
        field: samples
        mapping:
          project_id: "{{row.project.project_id}}"
          case: "{{row.id}}"

  sampleObject:
    - from: sampleData
    - project:
        mapping:
          type: sample
          id: "{{row.sample_id}}"
    - project:
        mapping:
          case: [ {"id" : "{{row.case}}"}]
    - objectValidate:
        title: Sample
        schema: "{{config.schema}}"
    - emit:
        name: sample


  aliquotData:
    - from: sampleData
    - fieldProcess:
        field: portions
        mapping:
          sample: "{{row.sample_id}}"
          project_id: "{{row.project_id}}"
    - fieldProcess:
        field: analytes
        mapping:
          sample: "{{row.sample}}"
          project_id: "{{row.project_id}}"
    - fieldProcess:
        field: aliquots
        mapping:
          sample: "{{row.sample}}"
          project_id: "{{row.project_id}}"
    - project:
        mapping:
          type: aliquot
          id: "{{row.aliquot_id}}"

  aliquotAlias:
    - from: aliquotData
    - clean:
        fields:
          - aliquot_id
          - submitter_id
          - project_id
    - emit:
        name: table

  aliquotObject:
    - from: aliquotData
    - project:
        mapping:
          sample: [ {"id" : "{{row.sample}}"} ]
    - objectValidate:
        title: Aliquot
        schema: "{{config.schema}}"
    - emit:
        name: aliquot
