
class: sifter

name: annotatedAllele
outdir: ../../output/allele

config:
  vcfPath: ../../output-normalize/allele.annotated.vcf
  schema: ../../schema/


inputs:
  vcfData:
    tableLoad:
      input: "{{config.vcfPath}}"
      columns:
          - CHROM
          - POS
          - ID
          - REF
          - ALT
          - QUAL
          - FILTER
          - INFO

pipelines:
  transform:
    - from: vcfData
    - map:
        method: fix
        gpython: |
          header = "Allele | Annotation | Annotation_Impact | Gene_Name | Gene_ID | Feature_Type | Feature_ID | Transcript_BioType | Rank | HGVS.c | HGVS.p | cDNA.pos / cDNA.length | CDS.pos / CDS.length | AA.pos / AA.length | Distance | ERRORS / WARNINGS / INFO".split(" | ")
          def fix(row):
            row["start"] = int(row["POS"])
            row["end"] = row["start"] + len(row["REF"])
            t = row["INFO"].split("=")
            o = []
            if len(t) > 1:
              a = t[1].split(",")
              for i in a:
                b = dict(zip(header, i.split("|")))
                b["hgvsc"] = b["HGVS.c"]
                b["hgvsp"] = b["HGVS.p"]
                b["biotype"] = b["Transcript_BioType"]
                b["impact"] = b["Annotation_Impact"]
                b["annotation"] =  b["Annotation"]
                b["hugo_symbol"] = b["Gene_Name"]
                b["ensembl_gene"] = b["Gene_ID"]
                if b["Feature_Type"] == "transcript":
                  b["ensembl_transcript"] = b["Feature_ID"]
                aa = b["AA.pos / AA.length"]
                if len(aa):
                  aa_pos, aa_len = aa.split("/")
                  b["aa_pos"] = int(aa_pos)
                  b["aa_len"] = int(aa_len)
                cds = b["CDS.pos / CDS.length"]
                if len(cds):
                  cds_pos, cds_len = cds.split("/")
                  b["cds_pos"] = int(cds_pos)
                  b["cds_len"] = int(cds_len)
                cdna = b["cDNA.pos / cDNA.length"]
                if len(cdna):
                  cdna_pos, cdna_len = cdna.split("/")
                  b["cdna_pos"] = int(cdna_pos)
                  b["cdna_len"] = int(cdna_len)
                o.append(b)
            row["effects"] = o
            return row
    - project:
        mapping:
          id: "GRCh38:{{row.CHROM}}:{{row.POS}}:{{row.REF}}:{{row.ALT}}"
          submitter_id: "GRCh38:{{row.CHROM}}:{{row.POS}}:{{row.REF}}:{{row.ALT}}"
          project_id: Reference
          reference_bases: "{{row.REF}}"
          alternate_bases: "{{row.ALT}}"
          chromosome: "{{row.CHROM}}"
          genome: GRCh38
    - objectValidate:
        schema: "{{config.schema}}"
        title: Allele
    - emit:
        name: allele