


class: sifter

name: annotated_VCF_transform
outdir: ../../output-normalize/

config:
  jsonPath: ../../output-normalize/allele.merge.json.gz
  schema: ../../schema/


inputs:
  jsonData:
    jsonLoad:
      input: "{{config.jsonPath}}"

pipelines: 
  prepData:
    - from: jsonData
    - project:
        mapping:
          id: "."
    - tableWrite:
        output: allele.vcf
        header: "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tTUMOR\tNORMAL"
        skipColumnHeader: true
        columns:
          - chromosome
          - start
          - id
          - reference_bases
          - alternate_bases


