
class: sifter
outdir: ../../tables
name: uniprot_features

config:
  xmlPath: ../../source/uniprot/
  schema: ../../schema

inputs:
  loader:
    glob:
      xmlLoad: {}
      input: "{{config.xmlPath}}/uniprot_*_human.xml.gz"

pipelines:
  features:
    - from: loader
    - fieldProcess:
        field: uniprot
    - fieldProcess:
        field: entry
    - flatmap:
        method: ensemblInfo
        gpython: 
          $ref: fix.py
    - emit:
        name: final
